name: Deploy CI/CD

on:
  push:
    branches: 
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with: 
          php-version: '8.2'
          extensions: sqlite, xdebug
          coverage: xdebug

      - name: copy env file
        run: cp .env.example .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: ./vendor/bin/pest

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Set ssh key 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy to Server
        if: ${{ success() }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd apps
            cd movie-quotes-back-luka-trapaidze
            git pull
            composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            php artisan migrate:fresh
          EOF
    
  
